// <auto-generated />
namespace TaskScheduler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class GoalAndProjectMigration2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GoalAndProjectMigration2));
        
        string IMigrationMetadata.Id
        {
            get { return "201803052027268_GoalAndProjectMigration2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
